extenda/actions

README.md, conventional-release/README.md, conventional-release/dist/index.js, maven/README.md, maven/action.yml, maven/dist/index.js, sonar-scanner/README.md, sonar-scanner/action.yml, sonar-scanner/dist/index.js, utils/README.md, utils/src/package.json, utils/src/versions.js
Add missing READMEs to all actions.
=> docs: Add READMEs

sonar-scanner/dist/index.js, sonar-scanner/src/index.js
=> Fix sonar-scanner to fail if QG isn't passed

README.md, setup-git/README.md, setup-git/action.yml, setup-git/dist/index.js, setup-git/package-lock.json, setup-git/package.json, setup-git/src/index.js
This action sets git credentials to make it possible to use Git CLI to push tags and commits to the GitHub repository.
=> feat: Add setup-git action

cloud-run/README.md, cloud-run/action.yml, cloud-run/dist/index.js, cloud-run/src/cloud-run-schema.js, cloud-run/src/cluster-info.js, cloud-run/src/create-namespace.js, cloud-run/src/gcloud-output.js, cloud-run/src/index.js, cloud-run/src/run-deploy.js, cloud-run/test/cluster-info.test.js, cloud-run/test/index.test.js, cloud-run/test/run-deploy.test.js, cloud-run/test/service-definition.test.js, setup-gcloud/README.md
This change introduces breaking changes to the cloud-run.yaml syntax. As this is pre-release versioned, we will not bump the major version.
=> feat: Refactor cloud-run to support GKE

.gitattributes, .github/workflows/commit.yml, sonar-scanner/package-lock.json, sonar-scanner/package.json, sonar-scanner/src/params.js, sonar-scanner/src/pull-request-info.js, sonar-scanner/test/params.test.js, sonar-scanner/test/pull-request-info.test.js, sonar-scanner/test/scan-msbuild.test.js
=> fix: Fix sonar-scanner pull request info for push event

sonar-scanner/src/index.js, sonar-scanner/src/params.js, sonar-scanner/src/pull-request-info.js, sonar-scanner/test/index.test.js, sonar-scanner/test/params.test.js
=> fix: Fix to only use deprecated PR params for sonar.extenda.io

cloud-run/dist/index.js, setup-gcloud/action.yml, setup-gcloud/dist/index.js, setup-gcloud/package-lock.json, setup-gcloud/package.json, setup-gcloud/src/index.js, setup-gcloud/src/setup-gcloud.js, setup-gcloud/test/setup-gcloud.test.js
It is now supported to opt-in to exporting `GOOGLE_APPLICATION_CREDENTIALS` for use in subsequent steps.
=> feat: Add export-default-credentials input to setup-gcloud

.github/workflows/commit.yml, README.md, setup-terraform/README.md, setup-terraform/action.yml, setup-terraform/dist/index.js, setup-terraform/package-lock.json, setup-terraform/package.json, setup-terraform/src/index.js, setup-terraform/test/index.test.js
Action to enable use of terragrunt and terraform in our pipelines.
=> feat: Add setup-terraform action

.github/workflows/pull_request.yml, commitlint/README.md, commitlint/action.yml
=> feat: Add relaxed mode for commitlint

cloud-run/dist/index.js, cloud-run/src/project-info.js, cloud-run/src/run-deploy.js, cloud-run/test/run-deploy.test.js
This PR implements adding labels for Cloud Run services, pointing project (clan) name, project_id, and environment.
=> feat(ELY-430): Add labels to cloudrun services

styra-das-deploy/README.md, styra-das-deploy/action.yml, styra-das-deploy/dist/index.js, styra-das-deploy/src/fetch-system-id.js, styra-das-deploy/src/index.js, styra-das-test/README.md, styra-das-test/action.yml, styra-das-test/entrypoint.sh
This PR also harmonizes input names with the IAM YAML property names for both DAS actions.
=> feat: Resolve DAS systemId from prefix and name

terraform-plan-comment/dist/index.js, terraform-plan-comment/src/generate-outputs.js, terraform-plan-comment/test/generate-outputs.test.js
This reverts commit a80a99d2e59f0e91a3216e59695b40c1a8c91422.
=> Revert "fix: Ignore plan.out files in cache directories (#201)"

sonar-scanner/action.yml, sonar-scanner/src/index.js, sonar-scanner/src/scan-msbuild.js, sonar-scanner/test/index.test.js
- Checks seem to fail because of an error in master.
- Get some diffs on "module.exports". Not sure if this is due to some inconsistency in the build environment, or if it can be ignored?
=> feat: Support adding custom msbuild Sonar arguments

cloud-run/dist/index.js, cloud-run/src/configure-domains.js
To configure DNS entries next commands must be executed:
```
gcloud dns record-sets transaction start
gcloud dns record-sets transaction add ...
gcloud dns record-sets transaction execute
```
Running these commands for different entries asynchronously produced an error:
```
ERROR: (gcloud.dns.record-sets.transaction.start) Transaction already exists at [transaction.yaml]
```
This PR fixes this issue
=> fix(ELY-632): Fix cloud-run configure multiple dns entries fail

cloud-run/dist/index.js, gcp-secret-manager/dist/index.js, gcp-secret-manager/src/secrets.js, gcp-secret-manager/test/secrets.test.js, iam-test-token/dist/index.js, maven/README.md, maven/action.yml, maven/dist/licenses.txt, maven/src/index.js, maven/src/nexus-credentials.js, maven/test/mvn.test.js, maven/test/nexus-credentials.test.js, nexus-auth-npm/dist/index.js, repository-dispatch/dist/index.js, slack-message/dist/index.js, slack-notify/dist/index.js, slack-notify/package-lock.json, slack-notify/package.json, slack-notify/src/slack-notify.js, slack-notify/test/slack-notify.test.js, sonar-scanner/src/sonar-credentials.js, sonar-scanner/test/sonar-credentials.test.js, status-check/dist/index.js, txengine-deploy/dist/index.js
The maven action can now automatically fetch nexus username and password if provided with a service account key.
=> feat(maven): Integrate GCP secret manager

README.md, pact-broker/README.md, pact-broker/action.yml, pact-can-i-deploy/README.md, pact-can-i-deploy/action.yml, pact-publish/README.md, pact-publish/action.yml, pact-tag-version/README.md, pact-tag-version/action.yml
A collection of pact-related actions to integrate pact and can-i-deploy checks in workflows.
=> feat: Add pact composite actions

cloud-run/dist/index.js, cloud-run/src/configure-domains.js, cloud-run/test/configure-domains.test.js
Roll out support for reteailsvc-test.com.
=> feat: Add retailsvc-test.com for cloud-run services

.github/workflows/commit.yml, .github/workflows/pull_request.yml
=> build(deps): Update actions

README.md, nexus-auth-npm/README.md, nexus-auth-npm/action.yml, nexus-auth-npm/dist/index.js, nexus-auth-npm/src/index.js, nexus-auth-npm/src/npmrc.js, nexus-auth-npm/test/index.test.js, nexus-auth-npm/test/npmrc.test.js
A Feature to resolve this issue https://extendaretail.slack.com/archives/CPRBERCRG/p1652791052903789
=> feat(nexus-auth-npm): Add publish config flag

sonar-scanner/src/index.js, sonar-scanner/src/scan.js, sonar-scanner/test/scan.test.js
Add support for yarn:
- Auto detect by yarn.lock
- Add 'yarn' scanner option
=> feat(sonar): Add yarn support

README.md
Add cloud-deploy to contents and update actions in example.
=> docs: Update README [skip ci]

cloud-deploy/README.md
=> docs(cloud-deploy): Fix Kubernetes examples [skip ci]

.scripts/rebase-dependabot-pr.py
=> chore: Add script to ease rebase of dependabot PR
