- README.md
- cloud-run/package.json
- conventional-release/package.json
- conventional-version/package.json
- docker/package.json
- gcp-secret-manager/package.json
- jira-release/package.json
- jira-releasenotes/package.json
- maven/package.json
- rs-create-installerpkg/package.json
- rs-permission-converter/package.json
- setup-gcloud/package.json
- setup-git/package.json
- setup-msbuild/package.json
- setup-nuget-sources/package.json
- slack-message/package.json
- sonar-scanner/package.json
- utils/package.json
Continued effort to make the project easier to work with on Windows. This PR removes all the scripts from the sub-packages to focus on a working root build. Test, build and lint should now work on all platforms.
> build: Remove scripts from sub-packages

- jira-releasenotes/README.md
There is a missing dot at the beginning of the file name, `pre-commit-config.yaml` should be `.pre-commit-config.yaml`.
> docs(quickfix): Fix a typo in pre-commit file config name

- cloud-run/README.md
- cloud-run/dist/index.js
- cloud-run/src/cloud-run-schema.js
- cloud-run/src/run-deploy.js
- cloud-run/test/run-deploy.test.js
- cloud-run/test/service-definition.test.js
This is a breaking change for existing cloud-run configs. The motivation for the change is that we want teams to be aware of what memory and CPU they consume at all times.
> feat: Require CPU in cloud-run.yaml

- terraform-plan-comment/action.yml
- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/index.js
- terraform-plan-comment/test/index.test.js
This PR also reformats the output to collapse each module output individually.
> feat: Add footer in terraform-plan-comment

- terraform-plan-comment/action.yml
- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/generate-outputs.js
- terraform-plan-comment/src/index.js
- terraform-plan-comment/test/generate-outputs.test.js
This PR provides an additional parameter to specify the name of resource or regexp pattern for multiple ones to ignore in generated pull request comment.
The output doesn't omit if other resources also changed in the plan.
Adding next parameter
```
ignored-resources-regexp: 'module.project_factory.module.project-factory.module.gcloud_deprivilege.null_resource.run_command\[0\]'
```
to `tf-infra-gcp` repo organization pipeline will prevent of generating an annoying list of changes
> feat: Add ignored resources parameter to terraform-plan-comment

- terraform-plan-comment/action.yml
- terraform-plan-comment/dist/index.js
- terraform-plan-comment/package-lock.json
- terraform-plan-comment/package.json
- terraform-plan-comment/src/generate-outputs.js
- terraform-plan-comment/src/index.js
- terraform-plan-comment/test/generate-outputs.test.js
Without limits, the action runs `terraform show` for every found plan file in parallel. All terraform instances query GCP API, and requests are throttled resulting the lots of errors.
This PR adds the parameter to specify the maximum number of running terraform processes in parallel.
> fix: Limit terraform show concurency run

- cloud-run/README.md
This PR changes the order of the table to more obvious order.
* All required on top
* Since concurrency mentions CPU it should come after CPU for clarity
> docs: Change order in table

- cloud-run/dist/index.js
- cloud-run/src/cluster-info.js
- test-pod/dist/index.js
This PR ignores `hiidentity-*` projects; also adds an additional check to only one tribe project must be found
> fix: Fix cloud-run action to find tribe project

- cloud-run/dist/index.js
- cloud-run/src/run-deploy.js
- cloud-run/test/run-deploy.test.js
This PR fixes issue that cloud run deploy is kinda stateful, i.e. if once deployed with --use-http2 removing this flag in following deploys actually doesn't disable http/2
> fix: Add --no-use-http2 argument to gcloud if disable-http2 option set

- cloud-run/action.yml
- cloud-run/dist/index.js
- cloud-run/src/index.js
- cloud-run/src/run-deploy.js
- cloud-run/test/index.test.js
- cloud-run/test/run-deploy.test.js
This PR rollback breaking change that was made by enabling http/2 by default.
New flag `enable-http2` was provided to enable HTTP/2.
Old flag `disable-http2` was kept to not break pipelines, that already implemented to fix the services
> fix: Disable HTTP/2 by default. Add flag to enable it

- cloud-run/dist/index.js
- cloud-run/src/run-deploy.js
- cloud-run/src/wait-revision.js
- cloud-run/test/run-deploy.test.js
- cloud-run/test/wait-revision.test.js
This PR is an attempt to workaround the following gcloud run deploy issue:
> Deploying container to Cloud Run for Anthos service [xxxxxxx] in namespace [default] of cluster [k8s-cluster]
> Deploying...
> Creating Revision.................failed
> Deployment failed
> ERROR: (gcloud.run.deploy) Revision “xxxxxxx-00013-loc” failed with message: 0/3 nodes are available: 3 Insufficient cpu..
When this happens, the `cloud-run` action will use `gcloud run revisions describe` and poll the revision status until it is successful, explicitly failed or the action times out.
> feat: Wait for revision if gcloud fails while cluster scales out

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/generate-outputs.js
- terraform-plan-comment/test/generate-outputs.test.js
This PR make ignoring `plan.out` files in `.terragrunt-cache` directories, which are created by Terragrunt recursive call.
It must fix the issue with multiple items in Github report comment
> fix: Ignore plan.out files in cache directories

- iam/README.md
- iam/action.yml
- iam/dist/index.js
- iam/package-lock.json
- iam/package.json
- iam/src/iam-schema.js
- iam/src/index.js
- iam/test/create-system.test.js
- iam/test/index.test.js
- iam/test/load-credentials.test.js
- utils/package-lock.json
Changes:
* Add support for multiple IAM definitions by allow a glob expression to be used as input
* Change how the action handles environments to ensure we ALWAYS publish to Hii Retail IAM production systems with a single exception: If we're deploying to staging AND we explicitly specify the staging URL, then we send permissions to the Hii Retail IAM staging system
* Minor tweaks to JSON Schema
* Fix unit tests
> feat(ELY-486): Add support for multiple IAM definitions at once

- test-pod/README.md
- test-pod/dist/index.js
- test-pod/src/run-pod.js
- test-pod/test/run-pod.test.js
Support for using custom env vars prefixed by `TESTPOD_` with the test-pod action. These variables will be exposed as-is to the container at runtime.
> feat: Support prefixed env vars in test-pod action

- test-pod/README.md
* Update README to show proper way to inject secrets in custom docker images.
* Add mention that we don't currently mount recursive files from working dir
> docs: Fix examples for test-pod

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/generate-outputs.js
- terraform-plan-comment/test/generate-outputs.test.js
This reverts commit 4633ede636ac807ff6641cef68bdb6a0d00c0c0e and reapply logic to ignore plan.out files in .terragrunt-cache directory. I tested with tf-infra-gcp and after move files out from the cache directory GHA worked fine. My decision about revert this commit to fixing the issue was mistaken.
> fix: Reapply: Ignore plan.out files in cache directories

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/generate-outputs.js
- terraform-plan-comment/test/generate-outputs.test.js
This reverts commit 837c1cf3b528cfc9e390ce5a37bae9c8ea9ea00d.
> Revert "fix: Reapply ignoring plan.out files in cache directories"

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/index.js
- terraform-plan-comment/test/index.test.js
Remove additional processing of footer to fix the mess in comments as https://github.com/extenda/tf-infra-gcp/pull/907#issuecomment-912238660
Originally footer looked like this:
https://github.com/extenda/tf-infra-gcp/pull/854#issuecomment-884047755
But as more information were added to the footer, it was reformatted to take less space:
https://github.com/extenda/tf-infra-gcp/pull/904#issuecomment-911463382
> fix: Don't remove newlines in footer

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/index.js
- terraform-plan-comment/test/index.test.js
In new Terraform version there are another text after the `Plan: X to add, X to change, X to destroy` line.
So summary line extracted by regexp
> fix: Make terraform-plan-comment to work with newer terraform versions

- terraform-plan-comment/dist/index.js
- terraform-plan-comment/src/index.js
Because there are special colorizing characters in the output
> fix: Fix regexp for terraform plan summary

- .github/workflows/commit.yml
The token for `::stop-commands::{token}` GA workflow command has to be a cryptographically secure and random string. Definitely not a string literal. See the [docs](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#stopping-and-starting-workflow-commands) for more details. The changeset follows the proposed pattern from the docs.
> build: Generate a sufficiently random token for stop-commands

- cloud-run/README.md
- cloud-run/action.yml
- cloud-run/dist/index.js
- cloud-run/dist/licenses.txt
- cloud-run/package-lock.json
- cloud-run/package.json
- cloud-run/src/index.js
- cloud-run/src/service-definition.js
- cloud-run/test/index.test.js
- cloud-run/test/service-definition.test.js
- kubernetes/dist/index.js
- kubernetes/dist/licenses.txt
- kubernetes/src/check-number-of-pods-running.js
- kubernetes/test/check-number-of-pods-running.test.js
- test-pod/dist/index.js
- test-pod/dist/licenses.txt
This change makes it easy to patch a cloud-run.yaml with deployment specific properties. It can for example be used to give a deployment different concurrency, CPU and memory depending on whether it is a test or staging system vs production. Another use case is to add additional environment variables not known until the GHA workflow executes.
> feat(cloud-run): Add ability to patch specification

- maven/README.md
Add single quote so that build don't fail due to missing single quotes.
`>>> Unexpected symbol: 'refs/heads/main' <<<`
> docs: Add single quote to maven RM.md

- README.md
- cloud-run/README.md
- docker/README.md
- kubernetes/README.md
- publish-openapi/README.md
- rs-create-installerpkg/README.md
- rs-permission-converter/README.md
- slack-message/README.md
- test-pod/README.md
- txengine-deploy/README.md
Deprecate actions that we no longer intend to support in the v1 tag. Deploy actions will be replaced by the general purpose cloud-deploy actions, while others are no longer in use or not possible to support due to broken APIs.
> docs: Add deprecation notices [skip ci]

- .github/workflows/commit.yml
Also removed setup-gcloud from windows as it is not important enough to warrant its test time.
> build(gha): Run acceptance and tests concurrently

- .github/workflows/commit.yml
- .github/workflows/pull-request.yml
Run a pull-request based workflow for dependabot changes. When dependabot runs, we generate the dist files and commit them with the extenda-devops-bot token. This will in turn trigger a new build that will run all the regular checks.
To optimize build time, regular commits jobs that require updated dist files are skipped for dependabot.
> build: Use separate dependabot workflow

- .github/dependabot.yml
- .scripts/generate-dependabot-yml.js
As we've found that groups won't span across different updates it makes sense to name each group after the action/module it updates.
> build: Update group names in dependabot.yml

- cloud-deploy/src/manifests/build-manifest.js
- cloud-deploy/src/manifests/build-manifests-gke.js
- cloud-deploy/src/utils/cloud-deploy.schema.json
- cloud-deploy/test/manifests/__snapshots__/build-manifest.test.js.snap
- cloud-deploy/test/manifests/build-manifest.test.js
Introduce a setting for `terminationGracePeriodSeconds` in the GKE manifest. This allows teams to specify a longer grace period than the default 90s.
> feat(cloud-deploy): Add termination-grace-period setting for GKE

- cloud-deploy-plan/src/create-comment.js
- cloud-deploy-plan/test/create-comment.test.js
Update cloud-deploy-plan to include the current value and the updated (new) value in the JSON properties table. This PR supports the old response with a single new value as well as the future response with an array containing the new and current value.
> feat(cloud-deploy-plan): Show current value in plan

- cloud-deploy/src/manifests/security-sidecar.js
- cloud-deploy/src/utils/security-cache-keys.js
- cloud-deploy/test/utils/security-cache-keys.test.js
Cache keys support is in beta preview on the security-authz sidecar. A properly defined cache key can boost throughput on the authorization sidecar.
> feat: Add cache keys to security-authz

- cloud-deploy/src/manifests/build-manifest.js
- cloud-deploy/src/manifests/build-manifests-gke.js
- cloud-deploy/src/manifests/build-manifests-run.js
- cloud-deploy/src/manifests/collector-sidecar.js
- cloud-deploy/test/manifests/__snapshots__/build-manifest.test.js.snap
- cloud-deploy/test/manifests/collector-sidecar.test.js
This PR will ensure that metrics components such as the collector or the pod-monitoring GKE resource are deployed in staging in the same way as in production.
It will also collect prometheus metrics from the security-authz sidecar if version exceeds v1.6.0 and the collector is used with preview-tag v2.2.2. 
**This PR does not bump the GA collector or GA security-authz.**
> feat(cloud-deploy): Collect metrics in staging and include security-authz
